#ifndef THREE_ADDR_CODE_H
#define THREE_ADDR_CODE_H

#include "ast.h"
#include <fstream>
#include <string>
#include <map>

using namespace std;

class ThreeAddrCodeGenerator {
private:
    ProgramNode* ast_root;
    ofstream& outcode;
    // Tracks the most recent temp name for each symbol
    map<string, string> symbol_to_temp;
    int temp_count;
    int label_count;

public:
    ThreeAddrCodeGenerator(ProgramNode* root, ofstream& out)
        : ast_root(root), outcode(out), temp_count(0), label_count(0) {} //initialization of variables

    void generate() {
        // Write a simple header explaining the TAC format
        outcode << "//========== THREE ADDRESS CODE ==========\n\n";
        outcode << "// This code was generated by a two-pass compiler\n";
        outcode << "// Format: \n";
        outcode << "// - t0, t1, etc. are temporary variables\n";
        outcode << "// - L0, L1, etc. are labels for jumps\n";
        outcode << "// - Operations follow the three-address code format\n\n";

        outcode << "// Three Address Code\n\n";

        
        if (ast_root) {
            ast_root->generate_code(outcode, symbol_to_temp, temp_count, label_count);
        }

        // Footer marker
        outcode << "\n//========== END OF CODE ==========\n";
    }

    // You may add helper methods here
};

#endif // THREE_ADDR_CODE_H
